import { DataTypes, Model } from 'sequelize';
import sequelize from '../database';

class Product extends Model {}

Product.init({
  id: { type: DataTypes.INTEGER, autoIncrement: true, primaryKey: true },
  name: { type: DataTypes.STRING, allowNull: false },
  description: { type: DataTypes.TEXT, allowNull: true },
  slug: { type: DataTypes.STRING, allowNull: false, unique: true },
  wattage: { type: DataTypes.FLOAT, allowNull: true },
  lumen: { type: DataTypes.FLOAT, allowNull: true },
  cct: { type: DataTypes.STRING, allowNull: true },
  beam_angle: { type: DataTypes.STRING, allowNull: true },
  dimming: { type: DataTypes.STRING, allowNull: true },
  is_featured: { type: DataTypes.BOOLEAN, allowNull: true },
  series_id: { type: DataTypes.INTEGER, allowNull: true },
  product_type_id: { type: DataTypes.INTEGER, allowNull: true },
  product_code: { type: DataTypes.STRING, allowNull: true },
  dimensions: { type: DataTypes.STRING, allowNull: true },
  cutout_size: { type: DataTypes.STRING, allowNull: true },
  mounting_type: { type: DataTypes.STRING, allowNull: true },
  trim_color: { type: DataTypes.STRING, allowNull: true },
  reflector_finish: { type: DataTypes.STRING, allowNull: true },
  orientation: { type: DataTypes.STRING, allowNull: true },
  lamp_source: { type: DataTypes.STRING, allowNull: true },
  system_lumen: { type: DataTypes.FLOAT, allowNull: true },
  cri: { type: DataTypes.STRING, allowNull: true },
  ip_rating: { type: DataTypes.STRING, allowNull: true },
  lifetime: { type: DataTypes.STRING, allowNull: true },
  driver_type: { type: DataTypes.STRING, allowNull: true },
  power_factor: { type: DataTypes.STRING, allowNull: true },
  input_voltage: { type: DataTypes.STRING, allowNull: true },
  warranty: { type: DataTypes.STRING, allowNull: true },
  colour: { type: DataTypes.STRING, allowNull: true },
  material: { type: DataTypes.STRING, allowNull: true },
  efficacy: { type: DataTypes.STRING, allowNull: true },
  optic: { type: DataTypes.STRING, allowNull: true },
  operating_temperature: { type: DataTypes.STRING, allowNull: true },
  datasheet: { type: DataTypes.STRING, allowNull: true },
  main_image_A: { type: DataTypes.STRING, allowNull: true },
  main_image_B: { type: DataTypes.STRING, allowNull: true },
  size_image: { type: DataTypes.STRING, allowNull: true },
  size_image_ai: { type: DataTypes.BOOLEAN, allowNull: true },
  application_image: { type: DataTypes.STRING, allowNull: true },
  photometric_image: { type: DataTypes.STRING, allowNull: true },
  ldt_family: { type: DataTypes.STRING, allowNull: true },
  ldt_beam_degrees: { type: DataTypes.INTEGER, allowNull: true },
  ldt_file: { type: DataTypes.STRING, allowNull: true },
  featured_image: { type: DataTypes.STRING, allowNull: true },
  vendor_code: { type: DataTypes.STRING, allowNull: true },
  vendor_model: { type: DataTypes.STRING, allowNull: true },
  external_id: { type: DataTypes.STRING, allowNull: true },
  external_source: { type: DataTypes.STRING, allowNull: true },
  created_at: { type: DataTypes.DATE, allowNull: true },
  updated_at: { type: DataTypes.DATE, allowNull: true },
}, {
  sequelize,
  modelName: 'Product',
  tableName: 'products',
  timestamps: false,
});

export default Product; 